version: '3.8'

services: 
    online-resto-backend:
        container_name: online-resto-serveur
        build: 
            context: ./
            dockerfile: Dockerfile
        command: npm start
        working_dir: /usr/src/app
        links: 
            - postgres
            - redis
        environment:
            POSTGRES_USER: claver
            POSTGRES_PASSWORD: claver
            POSTGRES_DB: resto-online
            POSTGRES_HOST: postgres
            JWTSECRET: ${JWTSECRET}
            REDIS_URI: redis://redis:6379
        volumes: 
            - "./:/usr/src/app"
            - "/usr/src/app/node_modules/"
        ports: 
            - "5001:5001"
        
    # Postgres
    postgres:
        
        build: ./postgres
        environment:
            POSTGRES_USER: claver
            POSTGRES_PASSWORD: claver
            POSTGRES_DB: resto-online
            POSTGRES_HOST: postgres
        ports: 
            - "5432:5432"
    
    #redis
    redis:
        image: redis
        ports: 
            - "6379:6379"
    