version: '3.8'

services: 
    online-resto-backend:
        container_name: online-resto-serveur
        build: 
            context: ./
            dockerfile: Dockerfile
        command: npm start
        working_dir: /usr/src/app
        links: 
            - postgres
        environment:
            POSTGRES_USER: claver
            POSTGRES_PASSWORD: claver
            POSTGRES_DB: resto-online
            POSTGRES_HOST: postgres
        volumes: 
            - ./:/usr/src/app
            - /usr/src/app/node_modules/
        ports: 
            - "5001:5001"
        
    # Postgres
    postgres:
        
        build: ./postgres
        environment:
            POSTGRES_USER: claver
            POSTGRES_PASSWORD: claver
            POSTGRES_DB: resto-online
            POSTGRES_HOST: postgres
        ports: 
            - "5432:5432"